.project, .pydevproject, .travis.yml, alfasim_sdk/hook_specs.py, appveyor.yml, tox.ini
Also add .project and .pydevproject
ASIM-2055
=> Add calculate_entrained_liquid_fraction to hook_specs.py

alfasim_sdk/hook_specs.py
Merge this PR just after https://github.com/ESSS/hookman/pull/15 is merged
=> Rename HooksSpecs to HookSpecs

alfasim_sdk/hook_specs.py
=> Update hook specs for calculate_entrained_liquid_fraction

alfasim_sdk/hook_specs.py, alfasim_sdk_api/api.h, alfasim_sdk_api/detail/api_pointers.h, alfasim_sdk_api/detail/bootstrap_linux.h, alfasim_sdk_api/detail/bootstrap_win.h
Add new hook for secondary variable update on alfasim-sdk and API function for getting plugin variable from simulation
ASIM-2346
=> Add new hook for secondary variable update on alfasim-sdk and API function for getting plugin variable from simulation

alfasim_sdk/models.py, alfasim_sdk/types.py, tests/test_models.py, tests/test_types.py
1) Add a new type -> ReferenceSelection
2) Rename the class DataReference to Reference
3) Rename Reference.value to Reference.ref_type
=> Fb asim 2525 refactoring data reference

alfasim_sdk/hook_specs.py
Split into 4 hooks (Mass, Momentum, Energy and Tracer)
=> Split compute_source_terms hook

alfasim_sdk/_alfasim_sdk_utils.py, alfasim_sdk/layout.py, alfasim_sdk/models.py, alfasim_sdk/types.py, tests/test_layout.py, tests/test_models.py, tests/test_types.py
=> Add support for tab and tabs components

alfasim_sdk/types.py, tests/test_types.py
=> Support for multiple reference only for tracers

alfasim_sdk/_alfasim_sdk_utils.py, alfasim_sdk/layout.py, alfasim_sdk/models.py, alfasim_sdk/types.py, tests/test_types.py
=> Add support for internal references on Reference field

alfasim_sdk_api/api.h, alfasim_sdk_api/common.h, alfasim_sdk_api/detail/api_pointers.h, alfasim_sdk_api/detail/bootstrap_linux.h, alfasim_sdk_api/detail/bootstrap_win.h
=> Add tracer data reference and tracer input data API functions

alfasim_sdk_api/api.h, alfasim_sdk_api/detail/api_pointers.h, alfasim_sdk_api/detail/bootstrap_linux.h, alfasim_sdk_api/detail/bootstrap_win.h
This function will allow the access of state variables already calculated.
=> Add get_state_variable_array to API

alfasim_sdk_api/common.h
to identify field "water_in_liquid_droplet"
=> Add macro FIELD_WATER_DROPLET_IN_LIQUID 

alfasim_sdk/types.py, alfasim_sdk_api/api.h, alfasim_sdk_api/detail/api_pointers.h, alfasim_sdk_api/detail/bootstrap_linux.h, alfasim_sdk_api/detail/bootstrap_win.h, tests/test_types.py
This pull request adds support for FilePath type
=> Add FilePath type

alfasim_sdk_api/api.h, alfasim_sdk_api/detail/api_pointers.h, alfasim_sdk_api/detail/bootstrap_linux.h, alfasim_sdk_api/detail/bootstrap_win.h
=> Add multiple-reference related API functions

alfasim_sdk_api/common.h, alfasim_sdk_api/detail/api_pointers.h, alfasim_sdk_api/detail/bootstrap_linux.h, alfasim_sdk_api/detail/bootstrap_win.h
After this is merged, there'll be no definitions of functions wrongly defined in header files
=> Overhaul plugis api

alfasim_sdk_api/detail/bootstrap_linux.h, alfasim_sdk_api/detail/bootstrap_win.h
=> Fb asim 606 merge with master

alfasim_sdk/constants.py, alfasim_sdk/context.py, tests/test_context.py
It is important to the plugins to check if an incompatible Hydrodynamic Model is set.
=> Add new HydrodynamicModelType to HydrodynamicModelInfo

alfasim_sdk/cli.py, poetry.lock, pyproject.toml
=> Create a minimal template for plugin

alfasim_sdk/constants.py, alfasim_sdk/context.py, tests/test_context.py
=> Move HydrodynamicModelType to constants.py and Add new entries

alfasim_sdk_api/api.h, alfasim_sdk_api/common.h, alfasim_sdk_api/detail/bootstrap_linux.h
These two new functions are in the new UCM Scope.
This is the First PR and it is just a preparation. The Docs were not linked yet because the functions may change in the next PR.
=> Add new api functions to the UCM scope

alfasim_sdk/constants.py
Add two new mfd models for three-phase flow
=> Fb aup 61 support 9 fields

docs/alfasim_sdk_api.cfg, docs/requirements.txt
=> Fix breath on alfasim docs

.pydevproject
This needs to be updated in order to LiClipse/pydev work properly.
=> Update pydevproject file

src/_alfasim_sdk/alfacase/alfacase_to_case.py, src/_alfasim_sdk/alfacase/case_description.py, src/_alfasim_sdk/alfacase/schema.py, tests/alfacase/test_case_description.py, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
=> Rename initial_fluid to fluid

src/_alfasim_sdk/alfacase/case_description.py, src/_alfasim_sdk/alfacase/schema.py, tests/alfacase/test_case_description.py, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
=> Add method ensure_unique_name

docs/source/_static/css/custom.css
=> Fix left side panel on small screen

HISTORY.rst, src/_alfasim_sdk/alfacase/alfacase_to_case.py, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
Change units (and category) of common testing input data
=> Fix units for volumetric flow rate at standard conditions

HISTORY.rst, docs/source/alfacase_definitions/LightComponentDescription.txt, src/_alfasim_sdk/alfacase/alfacase_to_case.py, src/_alfasim_sdk/alfacase/case_description.py, src/_alfasim_sdk/alfacase/schema.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_LightComponentDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
This parameter is no longer required as we are dropping support for the respective method on PVT side
(RFDAP-2502)
=> Remove B_parameter

HISTORY.rst, src/_alfasim_sdk/alfacase/schema.py, src/_alfasim_sdk/constants.py, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
Add new enum constant for walls without enviroment in pipe enviroment heat transfer coefficient model type.
=> Add new environment type to constants

HISTORY.rst, docs/source/alfacase_definitions/CaseOutputDescription.txt, docs/source/alfacase_definitions/TimeOptionsDescription.txt, src/_alfasim_sdk/alfacase/case_description.py, src/_alfasim_sdk/alfacase/schema.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_CaseOutputDescription_.txt, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_TimeOptionsDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
and trend/profile to CaseOutputDescription
=> Add new property to TimeOptionsDescription

src/alfasim_sdk/alfasim_sdk_api/api.h, src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h, src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_linux.h, src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_win.h
It is related to the UCM Liquid-Liquid System
=> Add new api function called get_liqliq_flow_pattern

docs/source/plugins/06_solver_hooks.rst, docs/source/plugins/99_1_solver_api_reference.rst, src/alfasim_sdk/_internal/hook_specs.py, src/alfasim_sdk/alfasim_sdk_api/api.h, src/alfasim_sdk/alfasim_sdk_api/common.h, src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h, src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_linux.h, src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_win.h
Also, Fix some internal links in the documentation, add missing docs (TwoPhaseSystem) and remove unused enumeration (WallLayerProperty).
=> Add Hooks for Liquid-Liquid Point Model 

HISTORY.rst, docs/source/alfacase_definitions/SeparatorNodePropertiesDescription.txt, src/alfasim_sdk/_internal/alfacase/alfacase_to_case.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_SeparatorNodePropertiesDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
=> Renamed radius to diameter in separator model

src/alfasim_sdk/_internal/alfacase/case_description_attributes.py, src/alfasim_sdk/_internal/alfacase/generate_case_description_docstring.py
This should not cause problems with older versions of the `attr`
package.
=> Account for changes in `attr` package

HISTORY.rst, docs/source/plugins/99_1_solver_api_reference.rst, src/alfasim_sdk/_internal/hook_specs.py, src/alfasim_sdk/alfasim_sdk_api/api.h, src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h, src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_linux.h, src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_win.h
They are:
- get_number_of_fields
- get_number_of_phases
- get_number_of_layers
- get_number_of_phase_pairs
=> Add new API functions

docs/source/alfacase_definitions/LeakEquipmentDescription.txt, src/alfasim_sdk/__init__.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, src/alfasim_sdk/_internal/constants.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_LeakEquipmentDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
Support for external leak (leak from pipe to environment
=> Fb asim 4397 external leak

src/alfasim_sdk/_internal/constants.py
Forgot to add this on the merged PR, just a minor update of PIG enums docs.
=> Add documentation to PIG related enums ASIM-4380

CONTRIBUTING.rst, HISTORY.rst, docs/README.rst, docs/source/alfacase/api_reference.rst, docs/source/alfacase_definitions/PositionalPipeTrendDescription.txt, docs/source/alfacase_definitions/SurgeVolumeOptionsDescription.txt, src/alfasim_sdk/__init__.py, src/alfasim_sdk/_internal/alfacase/alfacase_to_case.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, tests/alfacase/test_alfacase_to_case.py, tests/alfacase/test_generate_case_description_docstring.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PositionalPipeTrendDescription_.txt, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_SurgeVolumeOptionsDescription_.txt, tests/alfacase/test_generate_case_schema.py, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
Added the new class (SurgeVolumeOptions) as part of the positional trends description instead of the base trend class, since it is the only type of trend which can effectively use that model.
=> Support SurgeVolumeOptions in alfacase ASIM-4510

CHANGELOG.rst, RELEASING.rst
Rename HISTORY to CHANGELOG, add date for 0.12.0 release, fix indent in CHANGELOG file
=> Release 0.12.0

CHANGELOG.rst, docs/source/alfacase_definitions/PipeDescription.txt, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, tests/alfacase/test_case_to_alfacase.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PipeDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
New edge association attributes ASIM-4574
=> Support flow pattern model and regime capturing mesh treshold in case description

docs/source/alfacase_definitions/PhysicsDescription.txt, src/alfasim_sdk/_internal/alfacase/alfacase_to_case.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PhysicsDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
This branch is to let user set a tuning coefficient for the relative viscosity emulsion model. This demand came from Petrobras and the idea is to help the user to adjust the model against field data
=> Fb asim 4675 tuning factor

docs/source/alfacase_definitions/PumpEquipmentDescription.txt, docs/source/alfacase_definitions/list_of_unit_for_angle_per_time.txt, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/units.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PumpEquipmentDescription_.txt, tests/alfacase/test_generate_list_of_units/test_generate_list_of_units_angle_per_time_.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
Reviewed units for speed, using only Hz, rad/s and rpm and fix esp_speed category
=> Reviewed esp speed unit

src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h
Simply changed `typedef` to `using`
=> Change typedef to using

.github/workflows/main.yml, .gitignore, README.rst, sonar-project.properties
=> Enable sonar cloud integration

src/alfasim_sdk/_internal/cli.py, tests/test_cli.py
=> Add the current sdk version to the created hmplugin file

docs/source/alfacase_definitions/PumpEquipmentDescription.txt, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, src/alfasim_sdk/_internal/constants.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PumpEquipmentDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
Was update the alfacase to have the enabled_density_correction variable.
[ASIM-5108](https://eden.esss.co/jira/browse/ASIM-5108)
=> ASIM-5108-Fix reference density behavior in ESP

CHANGELOG.rst, docs/source/alfacase_definitions/PumpEquipmentDescription.txt, src/alfasim_sdk/__init__.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, src/alfasim_sdk/_internal/constants.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PumpEquipmentDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
In this task, was added the possbility of user set in GUI the thermal efficiency model in a PumpEquipment.
=> ASIM - 5241 set variable thermal efficiency

CHANGELOG.rst, docs/source/alfacase_definitions/PumpEquipmentDescription.txt, src/alfasim_sdk/__init__.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/case_description_attributes.py, src/alfasim_sdk/_internal/alfacase/schema.py, src/alfasim_sdk/_internal/constants.py, tests/alfacase/test_case_description.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PumpEquipmentDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
=> Rb asim v23.1.0

tests/alfacase/test_case_description.py, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
Reference: ASIM-5218
Efficiency values defined in CaseDescriptions are in fraction, not in percentage.
=> Minor - Fix efficiencies values

docs/source/alfacase/api_reference.rst, docs/source/alfacase_definitions/FetkovichIPRDescription.txt, docs/source/alfacase_definitions/IPRModelsDescription.txt, src/alfasim_sdk/__init__.py, src/alfasim_sdk/_internal/alfacase/alfacase_to_case.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, tests/alfacase/test_alfacase_to_case.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_FetkovichIPRDescription_.txt, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_IPRModelsDescription_.txt, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_UndersaturatedOilIPRDescription_.txt, tests/alfacase/test_generate_case_schema.py, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
ASIM-5245
Add a `CaseDescription` of the Fetkovich IPR model.
=> Add Fetkovich IPR Case Description

src/alfasim_sdk/default_tasks.py, tests/test_invoke.py
This PR will add the `install_dir` parameter to the installation tasks in order to the end user be able to customize where to install the plugins. Also, the tasks are renamed since the installation is no longer performed only for the user folder.
ASIM-4738
=> Update installation tasks

CHANGELOG.rst, docs/source/alfacase_definitions/NumericalOptionsDescription.txt, src/alfasim_sdk/_internal/alfacase/alfacase_to_case.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_NumericalOptionsDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt, tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
=> [ASIM-5231] Add field enable_fast_compositional to NumericalOptionsDescription

src/alfasim_sdk/result_reader/aggregator_constants.py
Adds two constants that contemplates the UQ results captions for their datasets.
[ASIM-5490](https://esss.atlassian.net/browse/ASIM-5490)
[ASIM-5490]: https://esss.atlassian.net/browse/ASIM-5490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ASIM-5490] Add constants to aggregator constanst file

src/alfasim_sdk/result_reader/aggregator.py, tests/conftest.py, tests/results/test_aggregator.py
This fix enable to read the global sensitivity analysis from their file result.
ASIM-5516
=> Read Global Sensitivity Analysis results

src/alfasim_sdk/result_reader/aggregator.py, tests/conftest.py, tests/results/test_aggregator.py
#364 was merged without applying the changes suggested in the reviews. This PR was created to address this and to fix minor things that had popup in the base branch CI.
=> Apply missing review changes and do some fixes

src/alfasim_sdk/result_reader/aggregator.py, tests/conftest.py, tests/results/test_aggregator.py
Change the GSA results filename to result to keep
the consistency with other results file in the ALFAsim.
ASIM-5486
=> [ASIM-5486] - Change GSA results file for consistency

CHANGELOG.rst
This release will match alfasim 23.2.0
=> Protocol release

src/alfasim_sdk/result_reader/aggregator_constants.py
Related Pr: https://github.com/ESSS/alfasim/pull/618
ASIM-5673
=> [ASIM-5673] - Save the uncertainty propagation results

docs/source/plugins/02_alfasim_sdk_by_example.rst, src/alfasim_sdk/_internal/types.py
Problems covered:
- Add missing variable associate to Table class;
- Fix enum class example input;
- Include <cmath> to compile example plugin;
- Change code-block to enhance view;
- Fix typos;
[PWPA-2063](https://esss.atlassian.net/browse/PWPA-2063)
[PWPA-2063]: https://esss.atlassian.net/browse/PWPA-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix documentation bugs and typos

docs/source/plugins/01_quick_start.rst, docs/source/plugins/02_alfasim_sdk_by_example.rst, docs/source/plugins/03_plugin_structure.rst, docs/source/plugins/04_application_hooks.rst, docs/source/plugins/05_solver_config_hooks.rst, docs/source/plugins/06_solver_hooks.rst, docs/source/plugins/99_2_user_interface_reference.rst, docs/source/plugins/99_3_solver_configuration_reference.rst, docs/source/plugins/index.rst
* Fix documentation for conda env creation
* General documentation review
=> Improve documentation

CHANGELOG.rst, docs/source/alfacase_definitions/PhysicsDescription.txt, src/alfasim_sdk/__init__.py, src/alfasim_sdk/_internal/alfacase/case_description.py, src/alfasim_sdk/_internal/alfacase/schema.py, src/alfasim_sdk/_internal/constants.py, tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PhysicsDescription_.txt, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
Add a new transfer mechanism for fluid materials composed by a parcel of radiation and convection.
ASIM-5943
=> [ASIM-5943] Add FluidMaterialConvectionCorrelation

CHANGELOG.rst, src/alfasim_sdk/result_reader/aggregator.py, src/alfasim_sdk/result_reader/reader.py, tests/conftest.py, tests/results/test_aggregator.py, tests/results/test_result_reader.py
Add support for the ALFAsim's server Results API while also improving the way users can interact with the UQ results.
ASIM-5920
=> Add support for Results API

src/alfasim_sdk/alfasim_sdk_api/api.h
Add documentation regarding the capability of the hook gets environmental temperature
=> Update alfasim-sdk documentation

.github/workflows/main.yml, docs/source/alfacase/case_description.quick_start.rst, docs/source/plugins/01_quick_start.rst, setup.cfg, src/alfasim_sdk/_internal/cli.py, src/alfasim_sdk/default_tasks.py, tests/test_invoke.py
Adjust some points that I've found in the alfasim-sdk workflow while I was reviewing it
Related: https://github.com/ESSS/hookman/pull/139
ASIM-5901
=> Review sdk workflow

tests/results/test_aggregator.py
Missing part from PR #440.
ASIM-5916
=> Fix aggregator test

CHANGELOG.rst, src/alfasim_sdk/_internal/alfacase/schema.py, src/alfasim_sdk/_internal/constants.py, tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
This MFD was replaced by the new two-layer, three-phase MFD with all the water dispersed in oil layer
=> Rename MFD ThreeLayersNoBubbleGasOilWater to TwoLayersGasOilWater
