alfasim_sdk/models.py
alfasim_sdk/types.py
tests/test_types.py

This pull request adds the `enable_expr` option on the `BaseField`.
Although this property is being introduced on the `BaseField`, the `enable_expr` it's an _optional_ property that the user can define or not.
In order to make this property be _optional_ and at the same time be _inherited_ by all objects, was necessary to include `kw_only=True` argument on the `attrs `declaration.

Add enable_expr option

---

alfasim_sdk/models.py
tests/test_models.py

This pull request changes the usage of `dir(class_)` to  ` class_.__dict__` to keep the declaration order intact
Also, this pull request adds a check to do not allow underscore at beginning of attributes names.

Keeping the declaration order.

---

alfasim_sdk_api/alfasim_sdk.h

Clang defines `unix` but GCC does not
EDEN-1807

Improve support for Linux compilers

---

alfasim_sdk_api/detail/bootstrap_linux.h
alfasim_sdk_api/detail/bootstrap_win.h

It can cause an access violation in a test that runs after another test
that failed and the dll handle wasn't cleaned setting nullptr

Set dll handle to nullptr after close the shared library

---

HISTORY.rst
alfasim_sdk/constants.py
alfasim_sdk/context.py
alfasim_sdk/hook_specs.py
alfasim_sdk/hook_specs_gui.py
alfasim_sdk/types.py
alfasim_sdk_api/api.h
alfasim_sdk_api/common.h
pyproject.toml

Renaming field liquid to oil. According to the literature of this research field, liquid is commonly referred to the sum of oil and water, not the oil itself

Fb asim 1167 change from liquid to oil

---

alfasim_sdk_api/api.h

Since the flow pattern enum has changed into alfasim
the API function `get_flow_pattern` documentation
must be updated also.

Update `get_flow_pattern` docs

---

.github/workflows/main.yml
docs/requirements.txt

I believe that everything is working normally now.
https://alfasim-sdk.readthedocs.io/en/update-docs-build-dependencies/

Update docs build dependencies

---

docs/source/alfacase/05_case_description_by_example.rst
docs/source/alfacase/alfacase.example.rst
docs/source/alfacase/alfacase.quick_start.rst
docs/source/alfacase/alfacase.rst
docs/source/alfacase/alfacase.syntax.rst
docs/source/alfacase/case_description.example.rst
docs/source/alfacase/case_description.quick_start.rst
docs/source/alfacase/case_description.rst
docs/source/alfacase/index.rst

This PR changes the hierarchy of files and, consequently, the structure of the left side menu (something I learned recently).
With this structure, I believe the sections are better visually organized
Before:
After:
https://alfasim-sdk--125.org.readthedocs.build/en/125/

Restructure the documentation to segment ALFAcase and case description.

---

docs/source/alfacase_definitions/PhysicsDescription.txt
src/alfasim_sdk/_internal/alfacase/case_description.py
src/alfasim_sdk/_internal/alfacase/generate_schema.py
src/alfasim_sdk/_internal/alfacase/schema.py
src/alfasim_sdk/_internal/hook_specs.py
tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PhysicsDescription_.txt
tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt

- Since the plugins are not supported in alfacase yet, the
emulsion_model_plugin_id must be ignored
- emulsion_model_plugin_id must not be optional, since it's not possible
to have None value

Fix emulsion_model_plugin_id instructions

---

HISTORY.rst
docs/source/plugins/06_solver_hooks.rst
docs/source/plugins/99_1_solver_api_reference.rst
src/alfasim_sdk/_internal/hook_specs.py
src/alfasim_sdk/alfasim_sdk_api/api.h
src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_linux.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_win.h

Since it is supposed to implement a correlation, now this hook receives double instead of an array of doubles.

Update relative emulsion viscosiry hook

---

.pre-commit-config.yaml

Update python version used by pre-commit.
Same as: https://github.com/ESSS/qmxgraph/pull/123
In qmx some tests failed due this and the problem was detected before merging, here all tests passed.
@nicoddemus, do you have any idea why?

Update pre commit config to use python 3.7

---

src/alfasim_sdk/_internal/alfacase/case_description.py
tests/alfacase/test_alfatable.py
tests/alfacase/test_case_description.py
tests/common_testing/alfasim_sdk_common_testing/case_builders.py
tests/test_case_builders.py

The idea here is to create a constant PH table that is able to test some network equipments, such valves, pump and compressor. The results can be compared directly with the PT model as the same equations have been used.

ASIM-4933: Implement tests with constant PH tables

---

docs/source/alfacase/api_reference.rst
src/alfasim_sdk/__init__.py
src/alfasim_sdk/_internal/alfacase/alfacase.py
src/alfasim_sdk/_internal/alfacase/alfatable.py
src/alfasim_sdk/_internal/alfacase/case_description.py
src/alfasim_sdk/_internal/alfacase/generate_schema.py
src/alfasim_sdk/_internal/constants.py
tests/alfacase/test_alfatable.py
tests/alfacase/test_case_description.py
tests/common_testing/alfasim_sdk_common_testing/case_builders.py
tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
tests/test_case_builders.py

The major idea os this PR is to refactor the PH tables model to keep it independent from the other models. A new TableDescription have been created exclusivly to the PH model.
With this approach the `TableType` enum is no more required, since the table check is done intirely based on the PVT model.
Also, now the `build_constant_pvt_table` build a `PvtModel` description that will fill the `ph` or `pt` table parameter with the right `TableDescription`.

fb-ASIM-4887 -> Refactor PH table model

---

src/alfasim_sdk/__init__.py
src/alfasim_sdk/_internal/constants.py

In ASIM-4926 it was necessary to add the EspParameters import in the module's __init__ and configure this enum with auto()

ASIM-4926-Change esp workflow

---

src/alfasim_sdk/__init__.py
src/alfasim_sdk/_internal/constants.py

Adds a enum to enable users in alfasim_gui select the viscosity correction model.

Add viscosity correction model enum

---

docs/source/alfacase_definitions/PumpEquipmentDescription.txt
src/alfasim_sdk/__init__.py
src/alfasim_sdk/_internal/alfacase/case_description.py
src/alfasim_sdk/_internal/alfacase/schema.py
src/alfasim_sdk/_internal/constants.py
tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PumpEquipmentDescription_.txt
tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py

Following ASIM-5017, it was necessary to add a `esp_parameters` field in `PumpEquipmentDescription` to cope with the two different `esp_tables`.

Add esp_parameters in PumpEquipmentDescription

---

.github/workflows/main.yml

Python 3.6 will no longer be supported on newer ubuntu version since it has reached end-of-live:
https://github.com/actions/setup-python/issues/544#issuecomment-1332535877

Force test job for py36/linux to use ubutu 20.04

---

src/alfasim_sdk/_internal/alfacase/case_description_attributes.py
tests/alfacase/test_case_description.py

This PR fix the method `to_curve` to return a curve if the length of `value` parameter is 0.
Tests from `test_configure_case_from_study.py` were crashing because the `GetAsCurve()` was returning nothing and the method `to_curve` did not know how to handle it.

Fix method `to_curve`

---

CHANGELOG.rst
docs/source/alfacase_definitions/PumpEquipmentDescription.txt
src/alfasim_sdk/__init__.py
src/alfasim_sdk/_internal/alfacase/case_description.py
src/alfasim_sdk/_internal/alfacase/schema.py
src/alfasim_sdk/_internal/constants.py
tests/alfacase/test_generate_case_description_docstring/test_generate_case_description_docstring_PumpEquipmentDescription_.txt
tests/alfacase/test_generate_case_schema/test_generate_schema_for_all_cases.txt
tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py

Update SDK definition of PumpEquipmentDescription
Update the PumpEquipment in case descriptio. Was removed the user_defined_esp_table and esp_parameters. Furthermore, was added the esp_manufacturer and esp_model.
[ASIM-5153](https://eden.esss.co/jira/browse/ASIM-5153)

ASIM-5153 - Update PumpEquipmentDescription 

---

src/alfasim_sdk/_internal/alfacase/case_description.py
src/alfasim_sdk/_internal/alfacase/case_description_attributes.py
tests/alfacase/test_case_description.py

Reference issue: ASIM-5237
Reference PR: https://github.com/ESSS/alfasim-sdk/pull/297
Empty `Curves` should be treated in right places, not generating data arbitrarily.

Reverting changes from PR 297

---

.readthedocs.yml
docs/requirements.txt
docs/source/conf.py

Previously, the config was using build.image, but this configuration will be no longer available after October, 16th 2023. See [this announcement](https://blog.readthedocs.com/use-build-os-config/)
Notice that I've added `graphviz` dependency to the `apt_packages` in the `readthedocs.yml` and removed from the `requirements.txt` because using `pip` the binary seems to not be available anymore, and the `graphviz` documentation suggests that it's preferable to use the package manager.
Finally, I tried changing the python version to be a newer one like 3.10, but there was some problems with the pinned version of sphinx and I opt to leave it to python 3.7 for now.
Close #317
ASIM-5369

Update readthedocs config to use build.os

---

.github/workflows/main.yml
CHANGELOG.rst
dev-environment.devenv.yml
requirements_dev.txt
setup.cfg
src/alfasim_sdk/__init__.py
src/alfasim_sdk/_internal/alfacase/alfatable.py
src/alfasim_sdk/_internal/alfacase/case_description_attributes.py
src/alfasim_sdk/_internal/alfacase/case_to_alfacase.py
src/alfasim_sdk/_internal/alfacase/generate_schema.py
src/alfasim_sdk/_internal/units.py
src/alfasim_sdk/default_tasks.py
tests/alfacase/test_alfacase_to_case.py
tests/plugins/test_models.py
tests/test_invoke.py
tox.ini

As a library, we should not use hardpins like this unless with a very good reason (preferably documented if a restriction is required).
* Removed explict dependency to `ruamel`, using instead the bundled library from `strictyaml` when needed.
* Removed old Python 3.6 and 3.7.
* Added support for Python 3.10.
Note: tried to add support for Python 3.11 and Python 3.12, however got a strange recursion error, we will need to investigate this later.
Closes #329.

Release 0.18.0: remove pins for `strictyaml`, py310, drop old Pythons

---

src/alfasim_sdk/_internal/alfacase/case_description.py

Part of the DCC-93/DCC-94.
Update the constant PVT model available in alfasim-sdk. Essentially, it includes derivatives with respect to enthalpy.
Additionally, the naming standard for derivatives has also been updated.

Add derivatives wrt to enthalpy to PH case description

---

src/alfasim_sdk/default_tasks.py
src/alfasim_sdk/testing/fixtures.py
tests/test_invoke.py

This PR consists of two small improvements:
- Update compile and package tasks' flags to forward the arguments from one to the other.
- Update some documentation of the tasks.
- Make `package-name` option of the package task optional, since we can infer this from plugin-id attribute
- Use the function `generate_alfacase_file` in the AlfasimRunnerFixture to be more concise.
ASIM-5261

Update invoke tasks and AlfasimRunner fixture

---

src/alfasim_sdk/_internal/alfacase/case_description.py
tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py

ASIM-5451
This fixes the issue with exporting and then importing an alfacase containing a pump.
I don't quite know how to test this. I haven't found a simple way to reproduce the problem (that doesn't involve launching the application, exporting and then importing the alfacase, then clicking the pump).

Set correct category for void_fractions array

---

CHANGELOG.rst
src/alfasim_sdk/_internal/alfacase/plugin_alfacase_to_case.py
src/alfasim_sdk/_internal/cli.py
src/alfasim_sdk_plugins/__init__.py
tests/alfacase/test_plugin_alfacase_to_case.py
tests/conftest.py
tests/test_cli.py

Now user plugins can have a namespace package named
`alfasim_sdk_plugins` (located in the `<plugin_id>/src/python` folder)
inside of which the plugin specific python source could be placed an
later imported.
At runtime alfasim/alfasim-sdk will import a root module also named
`alfasim_sdk_plugins` and manually edit `__path__` so the python's
import machinery look into the user plugins' namespace packages without
the need to further edit `sys.path` and cause possible import name
clashes.
ASIM-5419

Allow user plugins to import from other modules inside it

---

src/alfasim_sdk/result_reader/aggregator_constants.py

This allows HM results to be properly saved to files.
ASIM-5599

[ASIM-5599] Add History Matching results file keys to aggregator constants

---

src/alfasim_sdk/result_reader/aggregator.py
src/alfasim_sdk/result_reader/aggregator_constants.py
tests/conftest.py
tests/results/test_aggregator.py

Add History Matching metadata and reading functions to aggregator to allow reading HM results data.
ASIM-5600

[ASIM-5600] Read History Matching results

---

docs/source/alfacase_definitions/list_of_unit_for_velocity.txt
src/alfasim_sdk/_internal/units.py
tests/alfacase/test_generate_list_of_units/test_generate_list_of_units_velocity_.txt

Allowing velocity as mm/a because it is used in scaling plugin for Scaling growth velocity 
[DCC-196](https://esss.atlassian.net/browse/DCC-196)
[DCC-196]: https://esss.atlassian.net/browse/DCC-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allowing velocity as mm/a

---

docs/source/plugins/06_solver_hooks.rst
src/alfasim_sdk/_internal/hook_specs.py

[DCC-208](https://esss.atlassian.net/browse/DCC-208l)
Add a HOOK capable of updating plugin variables only once at the end of the time step computation (not on each step of Newton method - which is done by regular HOOK_UPDATE_PLUGINS_SECONDARY_VARIABLES)
[DCC-208]: https://esss.atlassian.net/browse/DCC-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a HOOK capable of updating plugin variables only once at the end of the time step computation

---

src/alfasim_sdk/alfasim_sdk_api/api.h

Update documentation that expose volumetric flow rate that can be used by plugins
https://esss.atlassian.net/browse/DCC-195

Expose volumetric flow rate that can be used by plugins

---

src/alfasim_sdk/alfasim_sdk_api/api.h

Added to be used by corrosion plugin's mixture model calculation.
The nomenclature `ks` was chosen instead of `ε` because it's already being used by `get_ucm_friction_factor_input_variable` hook
DCC-182

Add pipe roughness to API's get_simulation_array

---

src/alfasim_sdk/result_reader/aggregator.py
tests/conftest.py
tests/results/test_aggregator.py

Do so because results readers may need to know the info "var name X value" of the rest of the parametric vars (i.e. the disabled ones, that may or may not be dependent on the enabled/overriden vars) to fetch the results.
Related: https://github.com/ESSS/alfasim/pull/541.
ASIM-5586

Add parametric vars map to History Matching results metadata

---

src/alfasim_sdk/__init__.py

Due to the need to add type annotations to the plugins, we need to expose the Context object.
DCC-236

Expose Context object

---

src/alfasim_sdk/result_reader/aggregator.py
tests/results/test_aggregator.py

- Since History matching type is included into  UQType, the string values have a prefix 'HM-'

Uncertainty Propagation Structure

---

src/alfasim_sdk/default_tasks.py
tests/test_invoke.py

Improve the support of the debug of user plugins by letting the user provide a `cmake-extra-args` flag to the msvc task.
Also, fix an error prune default value for the `package-only` task's `dst` parameter
DCC-173

Improve debug of user plugins

---

CHANGELOG.rst
src/alfasim_sdk/result_reader/aggregator.py
src/alfasim_sdk/result_reader/aggregator_constants.py
tests/conftest.py
tests/results/test_aggregator.py

Add historic curves to the History Matching results metadata

---

docs/source/plugins/99_1_solver_api_reference.rst
src/alfasim_sdk/alfasim_sdk_api/api.h
src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_linux.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_win.h

PR description:
- Adds get_wall_properties, the method that a plugin developer user will use to get wall properties.

Add a possibility to plugin user gets wall properties

---

CHANGELOG.rst
docs/source/plugins/99_1_solver_api_reference.rst
src/alfasim_sdk/alfasim_sdk_api/api.h
src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_linux.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_win.h

PR description:
- It allows the plugin developer to add warning and information messages to the calc solver.
https://esss.atlassian.net/browse/ASIM-5645

Add logger capability to plugins developers

---

src/alfasim_sdk/alfasim_sdk_api/api.h

We've added the ks (roughness) variable to the CENTER GridScope, besides the FACE GridScope.
DCC-229

Update docs : ks available to all GridScope

---

src/alfasim_sdk/alfasim_sdk_api/api.h
src/alfasim_sdk/alfasim_sdk_api/detail/api_pointers.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_linux.h
src/alfasim_sdk/alfasim_sdk_api/detail/bootstrap_win.h

PR description:
- There was a bug at get_wall_material_names which was returning the wall names for all layers at once with char** (The char** doesn't know how many steps should be done to find the next wall name, since it does not have information about the length of the name). 
Solution: make the get_wall_material_name only return one wall name at once, by making the user provide the layer_id.

Make get_wall_material_names return material name for one layer id

---

environment.devenv.yml
src/alfasim_sdk/result_reader/aggregator.py
tests/results/test_aggregator.py

In recent hdf5 versions the old problem with non ascii paths apper to be fixed. A test to check this support have been added.
ASIM-5880
Related PR (commit) in alfasim: https://github.com/ESSS/alfasim/pull/731 (https://github.com/ESSS/alfasim/pull/731/commits/98f610fed968b8cc7b3dec45ce7702058575b5ed)

Drop the workaround to allow paths with non ascii chars

---

CHANGELOG.rst
src/alfasim_sdk/result_reader/aggregator.py
tests/conftest.py
tests/results/test_aggregator.py

- Since the shape of data is different than expected, the reader had to be updated to consider the correct shape of data.

Fix HM results reader

---

src/alfasim_sdk/result_reader/aggregator.py
src/alfasim_sdk/result_reader/reader.py
tests/results/test_result_reader.py

Add equality checks to the UQ result readers.

---

src/alfasim_sdk/alfasim_sdk_api/api.h

This PR is only informing that the alfasim tracers are available inside plugins

Informing that can get tracers already defined in Alfasim

---

src/alfasim_sdk/result_reader/aggregator.py

This constraint is not true anymore once we can have multiple results directories in the client/server architecture.
Related: https://github.com/ESSS/alfasim/pull/882.
ASIM-5916

Remove check of same result dir on concatenate_metadata function

---

CHANGELOG.rst
src/alfasim_sdk/result_reader/aggregator.py
src/alfasim_sdk/result_reader/reader.py
tests/results/test_aggregator.py
tests/results/test_result_reader.py

With the introduction of the ALFAsim client-server a result can be stored in multiples places (and eventually in multiple data stores), so the presence of this info along with the real result metadata doesn't make sense anymore.
ASIM-6121

Remove results dir from metadata objects

---

src/alfasim_sdk/testing/fixtures.py

- Handle ALFASIM_RUNNER environment variable that contains leading or trailing whitespace

Better handle $ALFASIM_RUNNER containing leading or trailing whitespaces

---

CHANGELOG.rst
setup.cfg

Barril did enter the 3.X series without API changes.
The error in "[docs/readthedocs.org:alfasim-sdk](https://app.readthedocs.org/projects/alfasim-sdk/builds/29643285/) — Read the Docs build failed!" is the same from master.

Update barril constrain
